version: '2'
services: 
    dotnetcore: 
        container_name: mymvc.web.compose
        # image: ':latest'
        build: .
        restart: always
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
        ports:
          - '5000:5000'
        command: MyMvc.Web.dll
        volumes: 
           - var/log/mymvc:/publish/log
