FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /app
COPY ./publish /app
EXPOSE 5000
ENV ASPNETCORE_URLS http://*:5000
ENTRYPOINT ["dotnet","MyMvc.Web.dll"]
####

# FROM microsoft/dotnet:latest AS build
# WORKDIR /app
 
# # copy csproj and restore as distinct layers
# COPY *.csproj ./
# RUN dotnet restore
 
# # copy everything else and build app
# COPY . ./
# RUN dotnet publish -c Release -o out
 
# FROM microsoft/dotnet:latest AS runtime
# WORKDIR /app
# COPY --from=build /app/out ./
# EXPOSE 5000
# ENTRYPOINT ["dotnet", "MyMvc.Web.dll"]


# COPY  ./publish /publish
# WORKDIR  /publish
# ENV ASPNETCORE_URLS http://*:5000
# ENV ASPNETCORE_PKG_VERSION 2.0.8
# EXPOSE 5000
# ENTRYPOINT ["dotnet"]
